var enJson={
  "Enter Your Message":"Enter Your Message",
  "Recent Chat":"Recent Chat",
  "Log in or sign up":"Log in or sign up",
  "Select Country":"Select Country",
  "Enter Phone Number":"Enter Phone Number",
  "Continue":"Continue",
  "or":"or",
  "Start":"Search",
  "Find Friends":"Find Friends",
  "Continue with Google":"Continue with Google",
  "Continue  with unknown login":"Continue  with unknown login",
  "By continuing,you agree to our":"By continuing,you agree to our",
  "Term of service  Privacy Policy  Content Policy":"Term of service  Privacy Policy  Content Policy",
  "Home":"Home",
  "Search":"Search",
  "Add":"Add",
  "Notifications":"Notifications",
  "Profile":"Profile",
  "Pandding friends requests":"Panding friends requests",
  "Accept":"Accept",
  "Reject":"Reject",
  "OTP Verification":"OTP Verification",
  "We have sent a verification code to":"We have sent a verification code to",
  "Resend OTP":"Resend OTP",
  "Resend SMS in ":"Resend SMS in ",
  "Edit Profile":"Edit Profile",
  "Your Ratings":"Your Ratings",
  "Settings":"Settings",
  "Change app language":"Change app language",
  "Dark theme":"Dark theme",
  "Privacy Policy":"Privacy Policy",
  "Share app":"Share app",
  "Install other apps":"Install other apps",
  "Log out":"Log out",
  "Search name":"Search name",
  "No recent chats":"No recent chats",
  "Complete your profile":"Complete your profile",
  "Change photo":"Change photo",
  "Need Storage Permission":"Need Storage Permission",
  "Upload failed":"Upload failed",
  "Name*":"Name*",
  "Email":"Email",
  "Bio":"Bio",
  "Birthdate":"Birthdate",
  "Gender":"Gender",
  "Enter email":"Enter email",
  "Enter name":"Enter name",
  "Enter bio":"Enter bio",
  "Male":"Male",
  "Female":"Female",
  "Save":"Save",
  "This number is not your login number":"This number is not your login number",
  "This email is not your login email":"This email is not your login email",
  "verification failed":"Verification failed",
  "Name is required":"Name is required",
  "Profile saved":"Profile saved",
  "Profile failed to save":"Profile failed to save",
  "Message is Empty":"Message is Empty",
  "Close":"Close"
};