var hiJson={
  "Enter Your Message":"अपना संदेश दर्ज करें",
  "Recent Chat":"हाल की चैट",
  "Log in or sign up":"लॉग इन या साइन अप",
  "Select Country":"देश चुनें",
  "Enter Phone Number":"फोन नंबर दर्ज",
  "Continue":"जारी रखना",
  "or":"या",
  "Start":"शुरू",
  "Find Friends":"मित्रों को खोजें",
  "Continue with Google":"Google के साथ जारी रखें",
  "Continue  with unknown login":"अज्ञात लॉगिन के साथ जारी रखें",
  "By continuing,you agree to our":"जारी रखकर, आप हमारी सहमति देते हैं",
  "Term of service  Privacy Policy  Content Policy":"सेवा की शर्तें  गोपनीयता नीति  सामग्री नीति",
  "Home":"होम",
  "Search":"खोज",
  "Add":"जोड़ना",
  "Notifications":"सूचनाएं",
  "Profile":"प्रोफ़ाइल",
  "Pandding friends requests":"पैंडिंग फ्रेंड रिक्वेस्ट",
  "Accept":"स्वीकार",
  "Reject":"अस्वीकार",
  "OTP Verification":"ओटीपी सत्यापन",
  "We have sent a verification code to":"हमने को सत्यापन कोड भेज दिया है",
  "Resend OTP":"ओटीपी पुनः भेजें",
  "Resend SMS in ":"एसएमएस फिर से भेजें",
  "Edit Profile":"प्रोफ़ाइल संपादित करें",
  "Your Ratings":"आपकी रेटिंग",
  "Settings":"समायोजन",
  "Change app language":"ऐप भाषा बदलें",
  "Dark theme":"काला थीम",
  "Privacy Policy":"गोपनीयता नीति",
  "Share app":"ऐप शेयर करें",
  "Install other apps":"अन्य ऐप्स इंस्टॉल करें",
  "Log out":"लॉग आउट",
  "Search name":"खोज नाम",
  "No recent chats":"हाल की कोई चैट उपलब्ध नहीं है",
  "Complete your profile":"अपनी प्रोफ़ाइल पूरी करें",
"Change photo":"तस्वीर बदलें",
"Need Storage Permission":"सैटोरेज अनुमति की आवश्यकता है",
"Upload failed":"अपलोड विफल",
"Name*":"नाम*",
"Number":"नंबर",
"Email":"ईमेल",
"Bio":"विवरण",
"Birthdate":"जन्म तिथि",
"Gender":"लिंग",
"Enter email":"ईमेल दर्ज करें",
"Enter name":"नाम दर्ज करें",
"Enter bio":"विवरण दर्ज करें",
"Male":"पुरुष",
"Female":"महिला",
"Save":"सेव",
"This number is not your login number":"This number is not your login number",
"This email is not your login email":"This email is not your login email",
"verification failed":"सत्यापन में विफल रहा",
"Name is required":"नाम आवश्यक है",
"Profile saved":"प्रोफ़ाइल सेव",
"Profile failed to save":"प्रोफ़ाइल सेव करने में विफल",
"Message is Empty":"संदेश खाली है",
"Close":"बंद करना"
};